### ISSUE TITLE
Split in 2 src files: main.c and transcode.c

### ISSUE THREAD

**Issue by WilliamTambellini** [ac000/ffmpeg-libs-audio-transcode#1]
@ac000  tks.
Would you mind if I split the scr code in 2 files: main.c (with just the main fn) and transcode.c ?
Best

**Comment by ac000** [comment]
Hey, feel free to do so in your own clone, but I'm not likely to apply such a thing here just to keep it simple as intended... (the patch would maybe also need to be regenerated...)

Thanks!
